version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: 
          name: Install sysstat
          command: |
            sudo apt-get update
            sudo apt-get install -y sysstat
            sudo systemctl enable sysstat
            sudo systemctl start sysstat


      - store_artifacts:
          path: /var/log/sysstat
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
